
name = "dota-match-announcer"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["*/1 * * * *", "*/15 * * * *"]

[vars]
# TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN" # This should be set as a secret
# PANDASCORE_TOKEN = "YOUR_PANDASCORE_TOKEN" # This should be set as a secret

[[d1_databases]]
binding = "D1"
database_name = "dota-match-announcer"
database_id = "14cfc1ee-16eb-496a-9393-5fe9ce421efa"
migrations_dir = "src/db"

[[kv_namespaces]]
binding = "NOTIFICATIONS_KV"
id = "583877d8a9a443b3beff55e5ca95b20f" # Placeholder
preview_id = "583877d8a9a443b3beff55e5ca95b20f" # Placeholder

