server:
  port: 8080

spring:
  application:
    name: dota-match-announcer
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:dotadb}
    username: postgres
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
    org.springframework.orm.jpa: info
    org.springframework.transaction: info

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-username: ${TELEGRAM_BOT_USERNAME:dota_match_announcer_bot}

pandascore:
  token: ${PANDASCORE_ACCESS_TOKEN}
  base-url: https://api.pandascore.co