server:
  port: 8080

spring:
  application:
    name: dota-match-announcer
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:dotadb}
    username: postgres
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}

pandascore:
  token: ${PANDASCORE_ACCESS_TOKEN}
  base-url: https://api.pandascore.co